export const reducerCases = {
  CREATE_NEW_CHAT: "CREATE_NEW_CHAT",
  SET_ALL_CONTACTS_PAGE: "SET_ALL_CONTACTS_PAGE",
  SET_MESSAGES: "SET_MESSAGES",
  SET_SOCKET: "SET_SOCKET",
  ADD_MESSAGES: "ADD_MESSAGES",
  SET_MESSAGE_SEARCH: "SET_MESSAGE_SEARCH",
  SET_USER_MESSAGE_LIST: "SET_USER_MESSAGE_LIST",
  // 通话相关
  SET_VIDEO_CALL: " SET_VIDEO_CALL",
  SET_VOICE_CALL: "SET_VOICE_CALL",
  SET_INCOMING_VIDEO_CALL: "SET_INCOMING_VIDEO_CALL",
  SET_INCOMING_VOICE_CALL: "SET_INCOMING_VOICE_CALL",
  END_CALL: "END CALL",
  // 是否接听
  IS_CONNECT: "IS_CONNECT",
  // 保存在线用户
  ONLINE_USERS: "ONLINE_USERS",
  // 删除在线用户
  DEL_ONLINE_USER: "DEL_ONLINE_USER",
  // 退出聊天界面
  EXIT_CHAT: "EXIT_CHAT",
  // 当前登录用户的消息
  USER_INFOS: "USER_INFOS",
  // 是否显示好友请求界面
  IS_SHOW_REQ: "IS_SHOW_REQ",
}