import '@/styles/globals.css'
import { Inter } from 'next/font/google'
const inter = Inter({ subsets: ['latin'] })
import { Provider } from '@/components'


export const metadata = {
  title: '畅聊',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Provider>
        {children}
      </Provider>
      </body>
    </html>
  )
}
